"use client";

import { useForm, SubmitHandler } from "react-hook-form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useEffect } from "react";

interface NoteEditorInputs {
  title: string;
  content: string;
  tags?: string;
}

interface NoteEditorProps {
  defaultValues?: NoteEditorInputs;
  onSubmit: (data: NoteEditorInputs) => void;
}

export default function NoteEditor({ defaultValues, onSubmit }: NoteEditorProps) {
  const {
    register,
    handleSubmit,
    setValue,
    getValues,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<NoteEditorInputs>({
    defaultValues,
  });

  useEffect(() => {
    reset(defaultValues || { title: "", content: "", tags: "" });
  }, [defaultValues, reset]);

  const submitHandler: SubmitHandler<NoteEditorInputs> = (data) => {
    onSubmit(data);
    reset({ title: "", content: "", tags: "" });
  };

  const handleAIImprove = async () => {
    const content = getValues("content").trim();
    if (!content) return toast.error("Content is empty!");

    try {
      const res = await fetch("/api/notes/ai-improve", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      const data = await res.json();
      if (data.error) return toast.error(data.error);

      setValue("content", data.result);
      toast.success("Content improved by AI!");
    } catch (err) {
      console.error(err);
      toast.error("AI Improve failed!");
    }
  };

  const handleAISummary = async () => {
    const content = getValues("content").trim();
    if (!content) return toast.error("Content is empty!");

    try {
      const res = await fetch("/api/notes/ai-summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      const data = await res.json();
      if (data.error) return toast.error(data.error);

      setValue("content", data.result);
      toast.success("Content summarized by AI!");
    } catch (err) {
      console.error(err);
      toast.error("AI summary failed!");
    }
  };

  const handleAITags = async () => {
    const content = getValues("content").trim();
    if (!content) return toast.error("Content is empty!");

    try {
      const res = await fetch("/api/notes/ai-tags", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      const data = await res.json();
      if (data.error) return toast.error(data.error);

      setValue("tags", data.result.join(", "));
      toast.success("Tags generated by AI!");
    } catch (err) {
      console.error(err);
      toast.error("AI Tags failed!");
    }
  };

  return (
    <form
      onSubmit={handleSubmit(submitHandler)}
      className="flex flex-col gap-4 w-full max-w-2xl mx-auto p-4 bg-white rounded-2xl shadow"
    >
      <div className="flex flex-col gap-1">
        <Label>Title</Label>
        <Input {...register("title", { required: "Title is required" })} />
        {errors.title && (
          <span className="text-red-500 text-sm">{errors.title.message}</span>
        )}
      </div>

      <div className="flex flex-col gap-1">
        <Label>Content</Label>
        <Textarea
          {...register("content", { required: "Content is required" })}
          rows={8}
        />
        {errors.content && (
          <span className="text-red-500 text-sm">{errors.content.message}</span>
        )}
      </div>

      <div className="flex flex-col gap-1">
        <Label>Tags (comma separated)</Label>
        <Input {...register("tags")} placeholder="tag1, tag2, tag3" />
      </div>

      <div className="flex gap-2 mt-2">
        <Button type="button" variant="outline" onClick={handleAIImprove}>
          AI Improve
        </Button>
        <Button type="button" variant="outline" onClick={handleAISummary}>
          AI Summary
        </Button>
        <Button type="button" variant="outline" onClick={handleAITags}>
          AI Tags
        </Button>
      </div>

      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Save Note"}
      </Button>
    </form>
  );
}
